"""The replay corpus: real journals, replayed against the current build.

Keep a corpus of real journals, replay them against every candidate build
in CI, and fail the build on divergence. This costs almost nothing to run,
catches determinism regressions before deploy rather than after, and is the
single highest-value test in a durable agent codebase.

The corpus ships as files rather than as fixtures built at test time. That
is the whole point: a journal recorded by version 7 has to still replay
under version 8, and a fixture regenerated by the build under test would
replay whatever that build happens to do.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from northstar_contracts import World
from northstar_runtime import (
    JournalExhausted,
    MemoryJournal,
    ReplayDivergence,
)

from workflow import RunContext, Suspended, refund_workflow

__all__ = [
    "JOURNAL_DIR",
    "CorpusEntry",
    "load_corpus",
    "record",
    "replay",
    "replay_all",
]

JOURNAL_DIR = Path(__file__).resolve().parent / "journals"


@dataclass(frozen=True)
class CorpusEntry:
    """One recorded journal, and what the workflow was called with.

    The arguments are stored alongside the records because a journal alone
    does not say what the run was asked to do, and a replay that has to
    guess the goal is not a replay.
    """

    name: str
    run_id: str
    order_id: str
    amount_cents: int
    records: list[dict[str, Any]]
    note: str = ""

    def journal(self) -> MemoryJournal:
        """A journal preloaded with this entry's records."""
        journal = MemoryJournal()
        for entry in self.records:
            journal.append(entry)
        return journal


def load_corpus(directory: Path = JOURNAL_DIR) -> list[CorpusEntry]:
    """Every recorded journal in the corpus, in filename order."""
    entries: list[CorpusEntry] = []
    for path in sorted(directory.glob("*.json")):
        payload = json.loads(path.read_text(encoding="utf-8"))
        entries.append(
            CorpusEntry(
                name=path.stem,
                run_id=payload["run_id"],
                order_id=payload["order_id"],
                amount_cents=int(payload["amount_cents"]),
                records=payload["records"],
                note=payload.get("note", ""),
            )
        )
    return entries


def replay(entry: CorpusEntry) -> dict[str, Any]:
    """Replay one journal against the current build.

    Nothing is executed and nothing is recorded. If the journal is complete
    this reproduces the final state exactly; if the workflow has since
    changed shape, it raises.

    Two outcomes are healthy and one is not. A *complete* journal replays
    to its terminal state. An *incomplete* one — the worker died — replays
    to the state at the moment it went away, which is the first question in
    any incident. Only a step the journal holds under a different name at
    that position is a failure, and that one raises.

    Raises:
        ReplayDivergence: The current build asks for a different step than
            the journal records at that position, which means the code
            moved under an in-flight run.
    """
    world = World()
    ctx = RunContext(
        run_id=entry.run_id,
        journal=entry.journal(),
        world=world,
        strict=True,
    )
    suspended = False
    incomplete = False
    try:
        state = refund_workflow(ctx, entry.order_id, entry.amount_cents)
        status = state.status
    except Suspended:
        suspended, status = True, "waiting_approval"
    except JournalExhausted:
        incomplete, status = True, "interrupted"
    return {
        "name": entry.name,
        "run_id": entry.run_id,
        "status": status,
        "suspended": suspended,
        "incomplete": incomplete,
        "replayed": list(ctx.replayed),
        "executed": list(ctx.executed),
        # Nothing may have executed. A replay that touches the world is not
        # a replay, and this is the assertion that says so.
        "world_untouched": world.ledger == [],
    }


def replay_all(directory: Path = JOURNAL_DIR) -> list[dict[str, Any]]:
    """Replay the whole corpus. Raises on the first divergence.

    Raises:
        ReplayDivergence: On any entry the current build cannot reproduce.
    """
    return [replay(entry) for entry in load_corpus(directory)]


def diverging(directory: Path = JOURNAL_DIR) -> list[str]:
    """Corpus entries the current build cannot replay, with the reason."""
    problems: list[str] = []
    for entry in load_corpus(directory):
        try:
            replay(entry)
        except ReplayDivergence as exc:
            problems.append(f"{entry.name}: {exc}")
    return problems


def record(
    name: str,
    run_id: str,
    order_id: str,
    amount_cents: int,
    records: list[dict[str, Any]],
    note: str = "",
    directory: Path = JOURNAL_DIR,
) -> Path:
    """Write one journal into the corpus.

    Used to regenerate the shipped files deliberately, which is the only
    way it should ever happen: a corpus the build under test regenerates is
    a corpus that agrees with whatever the build does.
    """
    directory.mkdir(parents=True, exist_ok=True)
    path = directory / f"{name}.json"
    path.write_text(
        json.dumps(
            {
                "run_id": run_id,
                "order_id": order_id,
                "amount_cents": amount_cents,
                "note": note,
                "records": records,
            },
            indent=2,
            sort_keys=True,
        )
        + "\n",
        encoding="utf-8",
    )
    return path
